---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnm-rata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bnm-rata
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bnm-rata
    spec:
      containers:
        - image: registry.github.com/File-V/dockerregistry/bnm-rata:v1
          name: bnm-rata
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: currency-rate-config
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8091
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8091
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 10
      imagePullSecrets:
        - name: regcred
